const levels=[
["Say Hello","Your very first C# line.","Start here. Learn what a program is and print one message.",`Console.WriteLine("Hello!");`,["C# programs can give instructions to the computer.","Console.WriteLine displays text.","Text goes inside quotation marks.","A semicolon ; ends the instruction."],`// Change the message\nConsole.WriteLine("Hello!");`,s=>/Console\.WriteLine\s*\(\s*"Hello, C# Buddy!"\s*\)/.test(s),`Type Console.WriteLine("Hello, C# Buddy!");`],
["Change the Message","Make the computer say something different.","You already know how to print text. Now make it say your own message.",`Console.WriteLine("I am learning C#!");`,["Copy the shape of the example.","Put your words inside quotes.","Keep Console.WriteLine exactly spelled this way.","End the line with ;."],`Console.WriteLine("I am learning C#!");`,s=>/Console\.WriteLine\s*\(\s*"[^"]+"\s*\)\s*;/.test(s)&&!/I am learning C#!/.test(s),`Replace the words inside the quotes with a different message.`],
["Your First Variable","Teach your program to remember a value.","A variable is a named box that stores information.",`string name = "Alex";\nConsole.WriteLine(name);`,["string means the variable stores text.","name is the variable's name.","= puts a value into the variable.","Later, name can be used instead of repeating the text."],`// Create a variable named name\n`,s=>/string\s+name\s*=\s*"[^"]+"\s*;/.test(s),`Use string name = "Alex";`],
["Numbers","Store a whole number.","Now your program can remember a number such as an age or score.",`int age = 14;\nConsole.WriteLine(age);`,["int stores whole numbers.","Give the variable a clear name.","Numbers do not need quotation marks.","You can use numbers in calculations."],`// Create score with the value 100\n`,s=>/int\s+score\s*=\s*100\s*;/.test(s),`Write int score = 100;`],
["Ask the User","Let someone type an answer.","Use Console.ReadLine() to wait for input.",`Console.Write("What is your name? ");\nstring name = Console.ReadLine() ?? "";\nConsole.WriteLine("Hello " + name);`,["Console.Write asks a question without moving to a new line.","Console.ReadLine waits for typing.","The result is text, so store it in a string.","Then print the answer."],`// Ask for a name and store it\n`,s=>/string\s+name\s*=\s*Console\.ReadLine\(\)/.test(s),`Use string name = Console.ReadLine();`],
["Make a Decision","Use if and else to choose what happens.","Programs become smart when they can make decisions.",`int age = 16;\nif (age >= 18)\n{\n    Console.WriteLine("Adult");\n}\nelse\n{\n    Console.WriteLine("Minor");\n}`,["if checks a condition.",">= means greater than or equal to.","else runs when the if condition is false.","Put instructions inside { }."],`int age = 16;\n// Add an if/else here\n`,s=>/if\s*\(\s*age\s*>=\s*18\s*\)/.test(s)&&/else/.test(s),`Check age >= 18, then add an else block.`],
["Repeat With a Loop","Make the computer repeat an instruction.","A loop saves you from writing the same line many times.",`for (int i = 1; i <= 5; i++)\n{\n    Console.WriteLine(i);\n}`,["i starts at 1.","The loop continues while i <= 5.","i++ adds one each time.","The line inside the braces repeats."],`// Print 1, 2, 3, 4, 5\n`,s=>/for\s*\(\s*int\s+i\s*=\s*1\s*;\s*i\s*<=\s*5\s*;\s*i\+\+\s*\)/.test(s),`Use for (int i = 1; i <= 5; i++).`],
["Build a Method","Package instructions into a reusable method.","Methods let you name a job and use it whenever you need it.",`static void Greet(string name)\n{\n    Console.WriteLine("Hello " + name);\n}\n\nGreet("Sam");`,["void means the method does not return a value.","name is a parameter.","The braces contain the method's instructions.","Call Greet(...) to use it."],`// Create Greet(string name)\n`,s=>/void\s+Greet\s*\(\s*string\s+name\s*\)/.test(s)&&/Console\.WriteLine/.test(s),`Create static void Greet(string name) { ... }`],
["Collections","Store several values together.","Arrays and lists let your program work with groups of data.",`string[] colors = { "Red", "Green", "Blue" };\nforeach (string color in colors)\n{\n    Console.WriteLine(color);\n}`,["An array can contain multiple values.","The first index is 0.","foreach visits each item.","The same pattern works for many kinds of data."],`// Create an array called colors\n`,s=>/string\[\]\s+colors\s*=/.test(s)&&/"Red"/.test(s)&&/"Green"/.test(s)&&/"Blue"/.test(s),`Use string[] colors = { "Red", "Green", "Blue" };`],
["Classes","Create your first object blueprint.","Classes are the foundation of object-oriented C#.",`class Player\n{\n    public string Name { get; set; }\n}\n\nPlayer player = new Player();\nplayer.Name = "Alex";`,["A class is a blueprint.","A property stores information about an object.","new creates an object.","Use a dot to access its properties."],`// Create a Car class with a Brand property\n`,s=>/class\s+Car/.test(s)&&/public\s+string\s+Brand\s*\\{\s*get\s*;\s*set\s*;\s*\\}/.test(s),`Inside class Car, add public string Brand { get; set; }`],
["Handle Errors","Keep your program calm when input is wrong.","try/catch lets you handle errors instead of letting the program stop.",`try\n{\n    int age = int.Parse(Console.ReadLine() ?? "0");\n}\ncatch (FormatException)\n{\n    Console.WriteLine("Please enter a number.");\n}`,["try contains code that might fail.","catch handles a particular error.","FormatException can happen when text is not a number.","Give the user a useful message."],`// Add try/catch\n`,s=>/try\s*\\{/.test(s)&&/catch\s*\(\s*FormatException\s*\)/.test(s),`Use try { ... } catch (FormatException) { ... }`],
["Final Project","Build a number guessing game.","You are ready to combine variables, input, conditions, and loops.",`int secret = 7;\nint guess = 0;\n\nwhile (guess != secret)\n{\n    Console.Write("Guess: ");\n    guess = int.Parse(Console.ReadLine() ?? "0");\n\n    if (guess < secret) Console.WriteLine("Too low!");\n    else if (guess > secret) Console.WriteLine("Too high!");\n    else Console.WriteLine("Correct!");\n}`,["Choose a secret number.","Ask the player for a guess.","Compare the guess with if/else.","Repeat until the guess is correct."],`int secret = 7;\n// Read a guess and compare it\n`,s=>/int\s+secret\s*=\s*7\s*;/.test(s)&&/Console\.ReadLine/.test(s)&&/if\s*\(/.test(s)&&/else/.test(s),`You need Console.ReadLine(), an if comparison, and an else branch.`]
];

let current=Number(localStorage.getItem("cb-level")||0);
let done=JSON.parse(localStorage.getItem("cb-levels-done")||"[]");
let dark=localStorage.getItem("cb-dark")==="1";
const unlocked=i=>i===0||done.includes(i-1);
const save=()=>{localStorage.setItem("cb-level",current);localStorage.setItem("cb-levels-done",JSON.stringify(done));};
const pct=()=>Math.round(done.length/levels.length*100);
function updateTop(){document.getElementById("percent").textContent=pct()+"%";document.getElementById("topProgress").style.width=pct()+"%";document.getElementById("sideMessage").textContent=done.length===levels.length?"Course complete!":done.length?"Keep going!":"Let's learn!";}
function renderNav(){
  document.getElementById("levelNav").innerHTML=levels.map((l,i)=>{
    const lock=!unlocked(i), ok=done.includes(i);
    return `<button class="level-link ${i===current&&!lock?"active":""} ${ok?"done":""} ${lock?"locked":""}" data-i="${i}" ${lock?"disabled":""}><span class="level-num">${ok?"✓":lock?"🔒":i+1}</span><span>Level ${i+1}: ${l[0]}</span></button>`;
  }).join("");
  document.querySelectorAll(".level-link:not([disabled])").forEach(b=>b.onclick=()=>openLevel(+b.dataset.i));
}
function openLevel(i){if(!unlocked(i))return;current=i;save();document.getElementById("courseHome").hidden=true;document.getElementById("levelScreen").hidden=false;renderLevel();scrollTo(0,0);}
function renderHome(){
  document.getElementById("courseHome").hidden=false;document.getElementById("levelScreen").hidden=true;
  document.getElementById("courseHome").innerHTML=`<div class="hero"><div class="hero-art"><img src="mascot.png" alt="C# Buddy teddy bear"></div><div class="hero-copy"><span class="pill">🐻 BEGINNER C# COURSE</span><h1>Learn C# <span>one level at a time.</span></h1><p>Start with one tiny instruction, practice it, then unlock the next skill. No previous C# experience needed.</p><div class="chips"><span class="chip">🌱 Start easy</span><span class="chip">🧩 Practice every level</span><span class="chip">🏆 Build a project</span></div></div></div>
  <section class="course-card"><h2 class="home-title">Your C# adventure</h2><p class="home-sub">Complete a level to unlock the next one. Each level has a simple explanation, a worked example, a tiny task, and a hint if you get stuck.</p><div class="course-progress"><b>${done.length} of ${levels.length} levels complete</b><span>${pct()}%</span></div><div class="bar"><i id="homeBar"></i></div><h3 class="section-label">Levels</h3><div class="level-grid">${levels.map((l,i)=>`<article class="level-card ${done.includes(i)?"done":""} ${!unlocked(i)?"locked":""}" data-level="${i}"><div class="num">${done.includes(i)?"✓":!unlocked(i)?"🔒":i+1}</div><div><h3>Level ${i+1} — ${l[0]}</h3><p>${l[2]}</p></div><span class="status">${done.includes(i)?"🏆":!unlocked(i)?"🔒":"→"}</span></article>`).join("")}</div></section>`;
  document.getElementById("homeBar").style.width=pct()+"%";
  document.querySelectorAll(".level-card:not(.locked)").forEach(c=>c.onclick=()=>openLevel(+c.dataset.level));
}
function renderLevel(){
  const l=levels[current], prev=current>0?levels[current-1]:null;
  document.getElementById("levelScreen").innerHTML=`<section class="hero"><div class="hero-art"><img src="mascot.png" alt="C# Buddy teddy bear coding"></div><div class="hero-copy"><span class="pill">LEVEL ${current+1} OF ${levels.length} ${done.includes(current)?"• COMPLETED":""}</span><h1>${l[0]}</h1><p>${l[2]}</p><div class="chips"><span class="chip">🌱 Beginner friendly</span><span class="chip">🎯 One skill</span><span class="chip">🧩 One exercise</span><button class="next-hero" id="heroNext">${current===levels.length-1?"🏆 Finish":"Next Level →"}</button></div></div></section>
  <div class="tabs"><button class="tab active">📖 Learn</button><button class="tab">💻 Example</button><button class="tab">🧩 Practice</button></div>
  <div class="content-grid"><div>
  <section class="card"><div class="lesson-head"><div class="lesson-big">${current+1}</div><div><h2>Step by step</h2><p>Take your time. You only need to understand this one idea before moving on.</p></div></div>
  <div class="lesson-intro">🐻 <b>C# Buddy says:</b> ${current===0?"Don't worry about memorizing anything. Your first job is simply to make the computer display a message.":`Level ${current+1} builds directly on what you learned before.`}</div>
  <h3 class="section-title">1. Read this first</h3><div class="steps">${l[4].map((x,i)=>`<div class="step"><div class="step-num">${i+1}</div><div><b>${x.split(".")[0]}</b><p>${x}</p></div></div>`).join("")}</div>
  <h3 class="section-title">2. Look at the example</h3><div class="copy-wrap"><button class="copy" id="copy">Copy</button><pre class="code">${esc(l[3])}</pre></div>
  <div class="tip" style="margin-top:12px">💡 <b>Beginner rule:</b> Don't rush. Read one line, say what it does in your own words, then read the next line.</div></section>
  <section class="card"><div class="exercise-head"><h3>3. Your turn</h3><span class="counter">${done.includes(current)?"✓ Completed":"Level task"}</span></div><p style="font-size:13px;color:var(--muted)">${l[5]}</p><textarea id="answer">${esc(l[6])}</textarea><div class="actions"><button class="primary" id="check">✓ Check My Code</button><button class="secondary" id="hintBtn">💡 Give Me a Hint</button></div><div id="feedback" class="feedback"></div><div id="hint" class="hint">${l[8]}</div></section>
  <div class="footer-nav"><button class="prev" id="prev" ${current===0?"disabled":""}>← Previous Level</button><button class="complete" id="next">${current===levels.length-1?"🏆 Complete Course":"Next Level →"}</button></div>
  </div><aside><div class="right-card"><div class="right-title">🐻 C# Buddy <span>your guide</span></div><div class="mascot-note"><img src="mascot.png" alt=""><div><b>${done.includes(current)?"You did it!":"You can do this!"}</b><small>${done.includes(current)?"This level is complete.":"Try the task before looking at the hint."}</small></div></div></div>
  <div class="right-card"><div class="right-title">🎯 Level goal</div><p>Learn one concept, complete one small exercise, then unlock the next level.</p></div>
  <div class="right-card"><div class="right-title">📈 Progress</div><p><b>${done.length}/${levels.length}</b> levels completed.</p><div class="bar"><i style="width:${pct()}%"></i></div></div></aside></div>`;
  document.getElementById("copy").onclick=async()=>{await navigator.clipboard.writeText(l[3]);document.getElementById("copy").textContent="Copied!";setTimeout(()=>document.getElementById("copy").textContent="Copy",1000)};
  document.getElementById("hintBtn").onclick=()=>document.getElementById("hint").style.display="block";
  document.getElementById("check").onclick=check;
  document.getElementById("prev").onclick=()=>{if(current>0){current--;save();renderLevel();scrollTo(0,0)}};
  document.getElementById("next").onclick=()=>{if(!done.includes(current))done.push(current);if(current<levels.length-1)current++;save();render();scrollTo(0,0)};
  document.getElementById("heroNext").onclick=()=>{if(!done.includes(current))done.push(current);if(current<levels.length-1)current++;save();render();scrollTo(0,0)};
}
function check(){
  const l=levels[current], ok=l[7](document.getElementById("answer").value), f=document.getElementById("feedback");
  f.className="feedback "+(ok?"good":"bad");f.textContent=ok?"Great job! 🎉 Level complete — the next level is now unlocked.":"Not quite yet. Read the instructions again, then try the code. You can use the hint.";
  if(ok&&!done.includes(current)){done.push(current);save();renderNav();updateTop();}
}
function esc(s){return s.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;")}
function render(){document.body.classList.toggle("dark",dark);updateTop();renderNav();renderHome();}
document.getElementById("theme").onclick=()=>{dark=!dark;localStorage.setItem("cb-dark",dark?"1":"0");render()};
document.getElementById("homeBtn").onclick=()=>{renderHome();scrollTo(0,0)};
document.getElementById("practiceBtn").onclick=()=>openLevel(Math.min(done.length,levels.length-1));
document.getElementById("projectBtn").onclick=()=>openLevel(levels.length-1);
document.getElementById("search").oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll(".level-link").forEach((b,i)=>b.style.display=levels[i][0].toLowerCase().includes(q)||levels[i][2].toLowerCase().includes(q)?"flex":"none")};
render();
