const lessons=[
{title:"Getting Started",desc:"Learn what C# is, set up your environment, and write your first program.",time:"15 min",code:`using System;\n\nclass Program\n{\n    static void Main(string[] args)\n    {\n        Console.WriteLine("Hello, C# Buddy!");\n    }\n}`,steps:[["What is C#?","C# is a modern language used to build apps, games, web services, and more."],["Set up your tools","Install the .NET SDK and choose an editor such as Visual Studio or VS Code."],["Write your first program","Use Console.WriteLine() to display text in the terminal."],["Run it","Build and run your console project and look for your message."]],exercise:{prompt:'Modify the code to print your name instead of "C# Buddy".',starter:`using System;\n\nConsole.WriteLine("Hello, C# Buddy!");`,test:s=>/Console\\.WriteLine\\s*\\(\\s*"Hello,\\s*(?!C# Buddy)/.test(s),hint:"Change the text inside Console.WriteLine(\"...\")."}},
{title:"Variables & Data Types",desc:"Store numbers, text, and true/false values in variables.",time:"20 min",code:`int score = 100;\ndouble price = 12.50;\nstring name = "Alex";\nbool isLearning = true;\n\nConsole.WriteLine(name);`,steps:[["Pick a type","Use int for whole numbers, double for decimals, string for text, and bool for true/false."],["Name the variable","Choose clear names such as score, name, or age."],["Assign a value","Use = to put a value into the variable."],["Use it","Print it or combine it with other values."]],exercise:{prompt:"Create an int variable named score with the value 100.",starter:"// Create score here",test:s=>/int\\s+score\\s*=\\s*100\\s*;/.test(s),hint:"Start with int score = 100;"}},
{title:"Input & Output",desc:"Make your programs interactive by asking the user for information.",time:"20 min",code:`Console.Write("What is your name? ");\nstring name = Console.ReadLine() ?? "";\nConsole.WriteLine("Hello " + name);`,steps:[["Ask","Tell the user what information you need."],["Read","Console.ReadLine() gets text typed by the user."],["Convert","Use int.Parse() when you need a whole number."],["Respond","Use the value in your program."]],exercise:{prompt:"Store a number typed by the user in an int variable called age.",starter:"// Read an age here",test:s=>/int\\s+age\\s*=\\s*int\\.Parse\\s*\\(\\s*Console\\.ReadLine\\(\\)/.test(s),hint:"Use int.Parse(Console.ReadLine())."}},
{title:"Conditions",desc:"Teach your program to make decisions with if, else if, and else.",time:"20 min",code:`int score = 72;\n\nif (score >= 50)\n{\n    Console.WriteLine("Pass");\n}\nelse\n{\n    Console.WriteLine("Try again");\n}`,steps:[["Make a condition","A condition is either true or false."],["Use if","The if block runs when the condition is true."],["Use else","The else block handles the other case."],["Compare","Use ==, !=, >, <, >=, and <=."]],exercise:{prompt:'Print "Adult" when age is at least 18; otherwise print "Minor".',starter:`int age = 16;\n// Add your if/else`,test:s=>/if\\s*\\(\\s*age\\s*>=\\s*18\\s*\\)/.test(s)&&/Console\\.WriteLine\\s*\\(\\s*"Adult"/.test(s)&&/else/.test(s)&&/Console\\.WriteLine\\s*\\(\\s*"Minor"/.test(s),hint:"Your condition should be age >= 18, followed by an else block."}},
{title:"Loops",desc:"Repeat code with for, while, and foreach loops.",time:"20 min",code:`for (int i = 1; i <= 5; i++)\n{\n    Console.WriteLine(i);\n}`,steps:[["Start","Set a counter such as i = 1."],["Check","The loop continues while the condition is true."],["Update","i++ adds one after each pass."],["Repeat","Put the code you want repeated inside the braces."]],exercise:{prompt:"Write a for loop that prints the numbers 1 through 5.",starter:"// Write your loop here",test:s=>/for\\s*\\(\\s*int\\s+i\\s*=\\s*1\\s*;\\s*i\\s*<=\\s*5\\s*;\\s*i\\+\\+\\s*\\)/.test(s),hint:"Use: for (int i = 1; i <= 5; i++)."}},
{title:"Methods",desc:"Create reusable pieces of code with named methods.",time:"20 min",code:`static void SayHello(string name)\n{\n    Console.WriteLine("Hello " + name);\n}\n\nSayHello("Sam");`,steps:[["Name the job","Give the method a clear name."],["Add parameters","Parameters let the method receive data."],["Choose a return type","void means it does not return a value."],["Call it","Write the method name followed by parentheses."]],exercise:{prompt:"Create a method named Greet that takes a string name and prints it.",starter:"// Create Greet here",test:s=>/void\\s+Greet\\s*\\(\\s*string\\s+name\\s*\\)/.test(s)&&/Console\\.WriteLine/.test(s),hint:"Start with static void Greet(string name) { ... }."}},
{title:"Arrays & Lists",desc:"Keep multiple values together and loop through them.",time:"20 min",code:`string[] fruits = { "Apple", "Banana", "Orange" };\n\nforeach (string fruit in fruits)\n{\n    Console.WriteLine(fruit);\n}`,steps:[["Array","An array stores a fixed-size group of values."],["Index","The first item is at index 0."],["List","List<T> can grow as your program runs."],["foreach","Visit every item without managing an index yourself."]],exercise:{prompt:"Create a string array named colors containing Red, Green, and Blue.",starter:"// Create colors here",test:s=>/string\\[\\]\\s+colors\\s*=/.test(s)&&/"Red"/.test(s)&&/"Green"/.test(s)&&/"Blue"/.test(s),hint:'Use string[] colors = { "Red", "Green", "Blue" };'}},
{title:"Classes & Objects",desc:"Learn the foundation of object-oriented programming.",time:"25 min",code:`class Player\n{\n    public string Name { get; set; }\n}\n\nPlayer player = new Player();\nplayer.Name = "Alex";`,steps:[["Class","A class is a blueprint for an object."],["Property","Properties describe data the object can hold."],["new","Create an instance using new."],["Dot notation","Access properties with object.Property."]],exercise:{prompt:"Create a class named Car with a public string property named Brand.",starter:"// Create Car here",test:s=>/class\\s+Car/.test(s)&&/public\\s+string\\s+Brand\\s*\\{\\s*get\\s*;\\s*set\\s*;\\s*\\}/.test(s),hint:"Inside class Car, add public string Brand { get; set; }."}},
{title:"Object-Oriented Programming",desc:"Combine classes, methods, properties, and objects into bigger programs.",time:"30 min",code:`class Dog\n{\n    public string Name { get; set; }\n\n    public void Bark()\n    {\n        Console.WriteLine(Name + " says woof!");\n    }\n}`,steps:[["Encapsulate","Keep related data and behavior together."],["Methods","Give objects actions they can perform."],["Properties","Give objects information they can store."],["Compose","Build bigger programs from smaller objects."]],exercise:{prompt:"Add a public void method named Speak to the Dog class that writes the dog's name.",starter:`class Dog\n{\n    public string Name { get; set; }\n    // Add Speak here\n}`,test:s=>/void\\s+Speak\\s*\\(\\s*\\)/.test(s)&&/Console\\.WriteLine/.test(s),hint:"Create public void Speak() { Console.WriteLine(Name); }."}},
{title:"Error Handling",desc:"Handle problems gracefully instead of letting your app crash.",time:"25 min",code:`try\n{\n    int age = int.Parse(Console.ReadLine() ?? "0");\n    Console.WriteLine(age);\n}\ncatch (FormatException)\n{\n    Console.WriteLine("Please enter a number.");\n}`,steps:[["Try","Put code that might fail inside try."],["Catch","Handle a specific error in catch."],["Explain","Give the user a useful message."],["Continue","Keep the rest of your program usable."]],exercise:{prompt:"Write a try/catch that catches FormatException.",starter:"// Add try/catch here",test:s=>/try\\s*\\{/.test(s)&&/catch\\s*\\(\\s*FormatException/.test(s),hint:"Use try { ... } catch (FormatException) { ... }."}},
{title:"Mini Projects",desc:"Put everything together by building a small number-guessing game.",time:"35 min",code:`int secret = 7;\nint guess = 0;\n\nwhile (guess != secret)\n{\n    Console.Write("Guess: ");\n    guess = int.Parse(Console.ReadLine() ?? "0");\n\n    if (guess < secret) Console.WriteLine("Too low!");\n    else if (guess > secret) Console.WriteLine("Too high!");\n    else Console.WriteLine("Correct!");\n}`,steps:[["Choose","Pick a secret number."],["Ask","Read the player's guess."],["Compare","Tell them too high, too low, or correct."],["Repeat","Keep asking until the answer is correct."]],exercise:{prompt:"Build the core guessing game: secret = 7, read a guess, then compare it with if/else.",starter:`int secret = 7;\n// Read guess and compare it`,test:s=>/int\\s+secret\\s*=\\s*7\\s*;/.test(s)&&/Console\\.ReadLine/.test(s)&&/if\\s*\\(/.test(s)&&/else/.test(s),hint:"You need a Console.ReadLine(), a comparison, and an else branch."}}
];

let current=Number(localStorage.getItem("cb-current")||0);
let done=JSON.parse(localStorage.getItem("cb-done")||"[]");
let dark=localStorage.getItem("cb-dark")==="1";

function save(){localStorage.setItem("cb-current",current);localStorage.setItem("cb-done",JSON.stringify(done))}
function progress(){return Math.round(done.length/lessons.length*100)}
function renderNav(){
  document.getElementById("lessonNav").innerHTML=lessons.map((l,i)=>`<button class="lesson-link ${i===current?"active":""} ${done.includes(i)?"done":""}" data-i="${i}"><span class="lesson-num">${done.includes(i)?"✓":i+1}</span><span>${l.title}</span></button>`).join("");
  document.querySelectorAll(".lesson-link").forEach(b=>b.onclick=()=>{current=+b.dataset.i;save();render()});
}
function escapeHtml(s){return s.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;")}
function render(){
  document.body.classList.toggle("dark",dark);
  const p=progress(); document.getElementById("percent").textContent=p+"%";document.getElementById("topProgress").style.width=p+"%";renderNav();
  const l=lessons[current];
  document.getElementById("lesson").innerHTML=`
  <section class="hero"><div class="hero-art"><img src="mascot.png" alt="C# Buddy teddy bear coding"></div><div class="hero-copy"><span class="pill">Lesson ${current+1} of ${lessons.length}</span><h1>${l.title}</h1><p>${l.desc}</p><div class="chips"><span class="chip">🌱 Beginner</span><span class="chip">◷ ~ ${l.time}</span><span class="chip">✓ ${done.includes(current)?"Complete":"In progress"}</span><button class="next-hero" id="heroNext">${current===lessons.length-1?"Finish Course":"Next Lesson →"}</button></div></div></section>
  <div class="tabs"><button class="tab active">📖 Learn</button><button class="tab" id="exampleTab">⌘ Example</button><button class="tab">▷ Try It Yourself</button><button class="tab">🏆 Challenge</button></div>
  <div class="content-grid"><div>
    <section class="card"><div class="lesson-head"><div class="lesson-big">${current+1}</div><div><h2>Let's learn it step by step</h2><p>${l.desc}</p></div></div>
    <h3 class="section-title">What you'll learn</h3><div class="steps">${l.steps.map((s,i)=>`<div class="step"><div class="step-num">${i+1}</div><div><b>${s[0]}</b><p>${s[1]}</p></div></div>`).join("")}</div>
    <h3 class="section-title">Example code</h3><div class="copy-wrap"><button class="copy" id="copy">Copy</button><pre class="code">${escapeHtml(l.code)}</pre></div>
    <div class="tip" style="margin-top:12px">💡 <b>C# Buddy tip:</b> Don't just read the code — type it yourself, change a value, and see what happens.</div></section>
    <section class="card"><div class="exercise-head"><h3>🧩 Interactive Exercise</h3><span class="counter">${done.includes(current)?"✓ Completed":"1 exercise"}</span></div><p style="font-size:13px;color:var(--muted)">${l.exercise.prompt}</p><textarea id="answer">${escapeHtml(l.exercise.starter)}</textarea><div class="actions"><button class="primary" id="check">✓ Check Code</button><button class="secondary" id="hintBtn">💡 Hint</button></div><div id="feedback" class="feedback"></div><div id="hint" class="hint">${l.exercise.hint}</div></section>
    <div class="footer-nav"><button class="prev" id="prev" ${current===0?"disabled":""}>← Previous</button><button class="complete" id="next">${current===lessons.length-1?"🏆 Finish Course":"Next: "+(lessons[current+1]?.title||"")+" →"}</button></div>
  </div><aside>
    <div class="right-card"><div class="right-title">🐻 C# Buddy <span>your guide</span></div><div class="mascot-note" style="margin-top:12px"><img src="mascot.png" alt=""><div><b>Keep going!</b><small>You're ${p}% of the way there. Every small program makes you better.</small></div></div></div>
    <div class="right-card"><div class="right-title">⚡ Quick facts</div><ul class="facts"><li>C# was created at Microsoft.</li><li>.NET is the platform used to run modern C# apps.</li><li>Console apps are a great place to start.</li></ul></div>
    <div class="right-card"><div class="right-title">🚀 Your mission</div><p>Finish every lesson, complete the exercises, then build your own mini-project.</p></div>
  </aside></div>`;
  document.getElementById("copy").onclick=async()=>{await navigator.clipboard.writeText(l.code);document.getElementById("copy").textContent="Copied!";setTimeout(()=>document.getElementById("copy").textContent="Copy",1000)};
  document.getElementById("hintBtn").onclick=()=>document.getElementById("hint").style.display="block";
  document.getElementById("check").onclick=check;
  document.getElementById("prev").onclick=()=>{if(current>0){current--;save();render();scrollTo(0,0)}};
  document.getElementById("next").onclick=next;
  document.getElementById("heroNext").onclick=next;
}
function check(){const l=lessons[current],ok=l.exercise.test(document.getElementById("answer").value),f=document.getElementById("feedback");f.className="feedback "+(ok?"good":"bad");f.textContent=ok?"Great job! Your code matches the exercise. 🎉":"Not quite yet — read the requirement, use the hint, and try again.";if(ok&&!done.includes(current)){done.push(current);save();renderNav();document.querySelector(".counter").textContent="✓ Completed";updateProgress()}}
function updateProgress(){const p=progress();document.getElementById("percent").textContent=p+"%";document.getElementById("topProgress").style.width=p+"%"}
function next(){if(!done.includes(current))done.push(current);if(current<lessons.length-1)current++;save();render();scrollTo(0,0)}
document.getElementById("theme").onclick=()=>{dark=!dark;localStorage.setItem("cb-dark",dark?"1":"0");render()};
document.getElementById("homeBtn").onclick=()=>{current=0;save();render();scrollTo(0,0)};
document.getElementById("practiceBtn").onclick=()=>document.getElementById("lesson").scrollIntoView({behavior:"smooth"});
document.getElementById("projectBtn").onclick=()=>{current=lessons.length-1;save();render();scrollTo(0,0)};
document.getElementById("search").oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll(".lesson-link").forEach((b,i)=>b.style.display=lessons[i].title.toLowerCase().includes(q)?"flex":"none")};
render();
